
# cargo-features = ["slice_patterns"]
[package]
name = "nuttchess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_core = "0.9.0"
rand_xorshift = "0.4.0"
